# .github/workflows/publish.yaml
name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      # 1. Récupère le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Met en place l'environnement Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 3. Installe les dépendances du projet
      - name: Install dependencies
        run: flutter pub get

      # 4. NOUVELLE ÉTAPE : Génère les fichiers de localisation
      #    Ceci corrige l'erreur "Couldn't resolve package 'flutter_gen'".
      - name: Generate localization files
        run: flutter gen-l10n

      # 5. Compile l'application pour Windows
      - name: Build Windows release
        run: flutter build windows --release

      # 6. Prépare le nom de la version et de l'archive
      - name: Prepare release details
        id: prepare_release
        run: |
          $TAG_NAME = "release-$(Get-Date -Format 'yyyy-MM-dd-HH-mm')"
          echo "TAG_NAME=$TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ASSET_NAME=gest-script-windows-$TAG_NAME.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # 7. Crée l'archive ZIP du build Windows
      - name: Create ZIP archive
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath ${{ env.ASSET_NAME }}

      # 8. Crée une nouvelle Release sur GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      # 9. Uploade l'archive ZIP en tant qu'asset de la Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
